### ISSUE TITLE
Key bindings please?

### ISSUE THREAD

**Issue by Endermanbugzjfc** [Fanhuaji/Sublime-Fanhuaji#1]

**Comment by jfcherng** [comment]
If you prefer the "quick panel" way just like what it is in the command palette:

![image](https://user-images.githubusercontent.com/6594915/90853849-e344b680-e3ad-11ea-9fd8-c40ef9013003.png) (ST 4083 preview)

```js
{ "keys": ["alt+q"], "command": "fanhuaji_convert_panel" },
```

---

If you prefer converting selected text with predefined configuration without any prompt:

https://github.com/Fanhuaji/Sublime-Fanhuaji/blob/141f1bac1f64a8c440f51f57a0f8d3c1911d599d/menus/Default.sublime-commands#L4-L9
```js
{
    "keys": ["alt+q"],
    "command": "fanhuaji_convert",
    "args": {
        "args": {
            "converter": "Simplified",
        },
    },
},
```

**Comment by Endermanbugzjfc** [comment]
Got it, thank you!
