### ISSUE TITLE
翻譯的選單反灰不能用

### ISSUE THREAD

**Issue by lp43** [Fanhuaji/Sublime-Fanhuaji#4]
![unnamed](https://github.com/user-attachments/assets/4b7f931d-4447-430f-8283-a2ba21bc5934)

請問sublime外掛繁化姬會反灰不能用（見圖）
是因為我公司防火牆鎖住嗎

**Comment by jfcherng** [comment]
在 ST 裡面按 `` ctrl+` `` 看一下 console 可能會有錯誤訊息，或是裡面的東西整個貼上來

**Comment by jfcherng** [comment]
等等   我似乎本地可以重現這個問題

**Comment by jfcherng** [comment]
原因是 https://github.com/packagecontrol/channel/pull/26#issuecomment-2321991887 , 稍後我會發新版本

**Comment by jfcherng** [comment]
感謝回報，已修復於 https://github.com/Fanhuaji/Sublime-Fanhuaji/releases/tag/4105-3.0.1
